name = "ivybridge"
wiki = "https://en.wikipedia.org/wiki/Ivy_Bridge_(microarchitecture)"
features = [
    "mmx",
    "sse",
    "sse2",
    "pni",
    "ssse3",
    "sse4_1",
    "sse4_2",
    "popcnt",
    "avx",
    "aes",
    "pclmulqdq",
    "fsgsbase",
    "rdrand",
    "f16c"
]
