level = 4
name = "haswell"
wiki = "https://en.wikipedia.org/wiki/Haswell_(microarchitecture)"
features = [
    "movbe",
    "mmx",
    "sse",
    "sse2",
    "pni",
    "ssse3",
    "sse4_1",
    "sse4_2",
    "popcnt",
    "avx",
    "avx2",
    "aes",
    "pclmulqdq",
    "fsgsbase",
    "rdrand",
    "fma",
    "bmi1",
    "bmi2",
    "f16c"
]
